name: contextual_logging
description: A log mixin that uses logger package and allows to make messages contextual.
version: 1.0.1
homepage: https://github.com/nivisi/contextual_logging
repository: https://github.com/nivisi/contextual_logging
issue_tracker: https://github.com/nivisi/contextual_logging/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  intl:
  logger:
  meta:
